apiVersion: v1
kind: Service
metadata:
  name: sso-app-v2
  labels:
    app: sso-app-v2
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: sso-app-v2

