apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sso-k8s
  namespace: argocd
spec:
  project: default
  source:
    # Replace the repoURL with your GitHub repo (HTTPS)
    repoURL: "https://github.com/TrueTruwowng/CICD"
    targetRevision: HEAD
    path: "k8s"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

# Notes:
#  - Replace <ORG_OR_USER> and <REPO> with your repository values.
#  - Argo CD will watch the `k8s` folder in that repo and deploy resources found there.
#  - This manifest must be applied to the `argocd` namespace (where Argo CD is installed).

