apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sso-k8s
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/truetruwowng/CICD"
    targetRevision: HEAD
    path: "k8s"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

# Notes:
#  - If your repository URL or path differs, edit this file before applying.
#  - If the repo is private, add the repo credentials in Argo CD (UI or `argocd repo add`).
