# GHCR image pull secret template for Kubernetes
# Replace <USERNAME> and <PERSONAL_ACCESS_TOKEN> with your GitHub username and a PAT that has `read:packages` scope.
# Create the secret locally with:
# kubectl create secret docker-registry ghcr-auth \
#   --docker-server=ghcr.io \
#   --docker-username=<USERNAME> \
#   --docker-password=<PERSONAL_ACCESS_TOKEN> \
#   --docker-email=you@example.com

apiVersion: v1
kind: Secret
metadata:
  name: ghcr-auth
  namespace: default
type: kubernetes.io/dockerconfigjson
# To create this file programmatically, use `kubectl create secret docker-registry ... --dry-run=client -o yaml` and apply.
data:
  .dockerconfigjson: <BASE64_DOCKERCONFIGJSON>

