apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-sso
  labels:
    app: my-sso
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-sso
  template:
    metadata:
      labels:
        app: my-sso
    spec:
      imagePullSecrets:
        - name: ghcr-auth
      containers:
        - name: sso
          image: ghcr.io/truetruwowng/sso-k8s:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

