apiVersion: v1
kind: Service
metadata:
  name: my-sso
  labels:
    app: my-sso
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
      protocol: TCP
  selector:
    app: my-sso

