# GitHub Actions CI: build, test, build & push Docker image to GHCR, update k8s manifest and push
name: CI - Build, Test, Publish image, Update k8s

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write
  packages: write

jobs:
  build-and-push:
    if: ${{ github.actor != 'github-actions[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Cache Maven local repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2-

      - name: Build with Maven (run tests)
        run: mvn -B -e -V package -DskipTests

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image to GHCR
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/truetruwowng/sso-k8s:${{ github.sha }}
            ghcr.io/truetruwowng/sso-k8s:latest

      - name: Update k8s deployment image and commit
        env:
          IMAGE: ghcr.io/truetruwowng/sso-k8s:${{ github.sha }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          # Replace the image line in the k8s deployment. Adjust the pattern if you use a different image name.
          if grep -q "image:" k8s/app-deployment.yaml; then
            sed -i "s|image: .*|image: $IMAGE|" k8s/app-deployment.yaml
          else
            echo "No image line found in k8s/app-deployment.yaml"
          fi
          git add k8s/app-deployment.yaml
          git commit -m "ci: bump image to $IMAGE [skip ci]" || echo "No changes to commit"
          git push origin HEAD:main
