name: CI/CD Build & Update Manifests

# Trigger on pushes to main; adjust branch as needed
on:
  push:
    branches: [ "main" ]

# Allow the workflow to push manifest updates back to the repository
permissions:
  contents: write
  packages: write

env:
  IMAGE_NAME: ghcr.io/truetruwowng/sso-k8s

jobs:
  build-and-update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Make Maven wrapper executable
        run: chmod +x ./mvnw

      - name: Build with Maven
        run: ./mvnw clean package -DskipTests

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ env.IMAGE_NAME }}:latest

      - name: Update k8s deployment image and commit
        env:
          IMAGE_NAME: ${{ env.IMAGE_NAME }}
          GITHUB_SHA: ${{ github.sha }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          # Replace the image line in the k8s deployment manifest with the new image tag
          # This assumes `k8s/app-deployment.yaml` contains a single `image:` entry for your app
          if grep -q "image:" k8s/app-deployment.yaml; then
            sed -i "s|image: .*|image: ${IMAGE_NAME}:${GITHUB_SHA}|" k8s/app-deployment.yaml || true
          else
            echo "Warning: no 'image:' line found in k8s/app-deployment.yaml"
          fi

          if [ -n "$(git status --porcelain)" ]; then
            git add k8s/app-deployment.yaml
            git commit -m "ci: update image to ${IMAGE_NAME}:${GITHUB_SHA} [skip ci]"
            git push origin HEAD:main
          else
            echo "No manifest changes to commit."
          fi
